import React from 'react';
export const complianceDetails = () => <div>compliance distinct</div>;
export const compliance_detail_0 = (p:any)=> <div>compliance 0 deadlines</div>;
export const compliance_detail_1 = (p:any)=> <div>compliance 1 checklists</div>;
export const compliance_detail_2 = (p:any)=> <div>compliance 2 flags</div>;
export const compliance_detail_3 = (p:any)=> <div>compliance 3 prior filings</div>;
export const compliance_detail_4 = (p:any)=> <div>compliance 4 deadlines</div>;
export const compliance_detail_5 = (p:any)=> <div>compliance 5 checklists</div>;
export const compliance_detail_6 = (p:any)=> <div>compliance 6 flags</div>;
export const compliance_detail_7 = (p:any)=> <div>compliance 7 prior filings</div>;
export const compliance_detail_8 = (p:any)=> <div>compliance 8 deadlines</div>;
export const compliance_detail_9 = (p:any)=> <div>compliance 9 checklists</div>;
export const compliance_detail_10 = (p:any)=> <div>compliance 10 flags</div>;
export const compliance_detail_11 = (p:any)=> <div>compliance 11 prior filings</div>;
export const compliance_detail_12 = (p:any)=> <div>compliance 12 deadlines</div>;
export const compliance_detail_13 = (p:any)=> <div>compliance 13 checklists</div>;
export const compliance_detail_14 = (p:any)=> <div>compliance 14 flags</div>;
export const compliance_detail_15 = (p:any)=> <div>compliance 15 prior filings</div>;
export const compliance_detail_16 = (p:any)=> <div>compliance 16 deadlines</div>;
export const compliance_detail_17 = (p:any)=> <div>compliance 17 checklists</div>;
export const compliance_detail_18 = (p:any)=> <div>compliance 18 flags</div>;
export const compliance_detail_19 = (p:any)=> <div>compliance 19 prior filings</div>;