import React from 'react';
export const notificationsDetails = () => <div>notifications distinct</div>;
export const notifications_detail_0 = (p:any)=> <div>notifications 0 deadline alerts</div>;
export const notifications_detail_1 = (p:any)=> <div>notifications 1 review</div>;
export const notifications_detail_2 = (p:any)=> <div>notifications 2 SEC</div>;
export const notifications_detail_3 = (p:any)=> <div>notifications 3 comments</div>;
export const notifications_detail_4 = (p:any)=> <div>notifications 4 deadline alerts</div>;
export const notifications_detail_5 = (p:any)=> <div>notifications 5 review</div>;
export const notifications_detail_6 = (p:any)=> <div>notifications 6 SEC</div>;
export const notifications_detail_7 = (p:any)=> <div>notifications 7 comments</div>;
export const notifications_detail_8 = (p:any)=> <div>notifications 8 deadline alerts</div>;
export const notifications_detail_9 = (p:any)=> <div>notifications 9 review</div>;
export const notifications_detail_10 = (p:any)=> <div>notifications 10 SEC</div>;
export const notifications_detail_11 = (p:any)=> <div>notifications 11 comments</div>;
export const notifications_detail_12 = (p:any)=> <div>notifications 12 deadline alerts</div>;
export const notifications_detail_13 = (p:any)=> <div>notifications 13 review</div>;
export const notifications_detail_14 = (p:any)=> <div>notifications 14 SEC</div>;
export const notifications_detail_15 = (p:any)=> <div>notifications 15 comments</div>;
export const notifications_detail_16 = (p:any)=> <div>notifications 16 deadline alerts</div>;
export const notifications_detail_17 = (p:any)=> <div>notifications 17 review</div>;
export const notifications_detail_18 = (p:any)=> <div>notifications 18 SEC</div>;
export const notifications_detail_19 = (p:any)=> <div>notifications 19 comments</div>;