import React from 'react';
export const frontendDetails = () => <div>frontend distinct</div>;
export const frontend_detail_0 = (p:any)=> <div>frontend 0 editor</div>;
export const frontend_detail_1 = (p:any)=> <div>frontend 1 XBRL tagger</div>;
export const frontend_detail_2 = (p:any)=> <div>frontend 2 calendar</div>;
export const frontend_detail_3 = (p:any)=> <div>frontend 3 editor</div>;
export const frontend_detail_4 = (p:any)=> <div>frontend 4 XBRL tagger</div>;
export const frontend_detail_5 = (p:any)=> <div>frontend 5 calendar</div>;
export const frontend_detail_6 = (p:any)=> <div>frontend 6 editor</div>;
export const frontend_detail_7 = (p:any)=> <div>frontend 7 XBRL tagger</div>;
export const frontend_detail_8 = (p:any)=> <div>frontend 8 calendar</div>;
export const frontend_detail_9 = (p:any)=> <div>frontend 9 editor</div>;
export const frontend_detail_10 = (p:any)=> <div>frontend 10 XBRL tagger</div>;
export const frontend_detail_11 = (p:any)=> <div>frontend 11 calendar</div>;
export const frontend_detail_12 = (p:any)=> <div>frontend 12 editor</div>;
export const frontend_detail_13 = (p:any)=> <div>frontend 13 XBRL tagger</div>;
export const frontend_detail_14 = (p:any)=> <div>frontend 14 calendar</div>;
export const frontend_detail_15 = (p:any)=> <div>frontend 15 editor</div>;
export const frontend_detail_16 = (p:any)=> <div>frontend 16 XBRL tagger</div>;
export const frontend_detail_17 = (p:any)=> <div>frontend 17 calendar</div>;
export const frontend_detail_18 = (p:any)=> <div>frontend 18 editor</div>;
export const frontend_detail_19 = (p:any)=> <div>frontend 19 XBRL tagger</div>;