import React from 'react';
export const reportsDetails = () => <div>reports distinct</div>;
export const reports_detail_0 = (p:any)=> <div>reports 0 filing report</div>;
export const reports_detail_1 = (p:any)=> <div>reports 1 XBRL report</div>;
export const reports_detail_2 = (p:any)=> <div>reports 2 compliance</div>;
export const reports_detail_3 = (p:any)=> <div>reports 3 filing report</div>;
export const reports_detail_4 = (p:any)=> <div>reports 4 XBRL report</div>;
export const reports_detail_5 = (p:any)=> <div>reports 5 compliance</div>;
export const reports_detail_6 = (p:any)=> <div>reports 6 filing report</div>;
export const reports_detail_7 = (p:any)=> <div>reports 7 XBRL report</div>;
export const reports_detail_8 = (p:any)=> <div>reports 8 compliance</div>;
export const reports_detail_9 = (p:any)=> <div>reports 9 filing report</div>;
export const reports_detail_10 = (p:any)=> <div>reports 10 XBRL report</div>;
export const reports_detail_11 = (p:any)=> <div>reports 11 compliance</div>;
export const reports_detail_12 = (p:any)=> <div>reports 12 filing report</div>;
export const reports_detail_13 = (p:any)=> <div>reports 13 XBRL report</div>;
export const reports_detail_14 = (p:any)=> <div>reports 14 compliance</div>;
export const reports_detail_15 = (p:any)=> <div>reports 15 filing report</div>;
export const reports_detail_16 = (p:any)=> <div>reports 16 XBRL report</div>;
export const reports_detail_17 = (p:any)=> <div>reports 17 compliance</div>;
export const reports_detail_18 = (p:any)=> <div>reports 18 filing report</div>;
export const reports_detail_19 = (p:any)=> <div>reports 19 XBRL report</div>;