import React from 'react';
export const templatesDetails = () => <div>templates distinct</div>;
export const templates_detail_0 = (p:any)=> <div>templates 0 10-K shell</div>;
export const templates_detail_1 = (p:any)=> <div>templates 1 10-Q shell</div>;
export const templates_detail_2 = (p:any)=> <div>templates 2 styles</div>;
export const templates_detail_3 = (p:any)=> <div>templates 3 boilerplate</div>;
export const templates_detail_4 = (p:any)=> <div>templates 4 10-K shell</div>;
export const templates_detail_5 = (p:any)=> <div>templates 5 10-Q shell</div>;
export const templates_detail_6 = (p:any)=> <div>templates 6 styles</div>;
export const templates_detail_7 = (p:any)=> <div>templates 7 boilerplate</div>;
export const templates_detail_8 = (p:any)=> <div>templates 8 10-K shell</div>;
export const templates_detail_9 = (p:any)=> <div>templates 9 10-Q shell</div>;
export const templates_detail_10 = (p:any)=> <div>templates 10 styles</div>;
export const templates_detail_11 = (p:any)=> <div>templates 11 boilerplate</div>;
export const templates_detail_12 = (p:any)=> <div>templates 12 10-K shell</div>;
export const templates_detail_13 = (p:any)=> <div>templates 13 10-Q shell</div>;
export const templates_detail_14 = (p:any)=> <div>templates 14 styles</div>;
export const templates_detail_15 = (p:any)=> <div>templates 15 boilerplate</div>;
export const templates_detail_16 = (p:any)=> <div>templates 16 10-K shell</div>;
export const templates_detail_17 = (p:any)=> <div>templates 17 10-Q shell</div>;
export const templates_detail_18 = (p:any)=> <div>templates 18 styles</div>;
export const templates_detail_19 = (p:any)=> <div>templates 19 boilerplate</div>;